services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      KEYBOARD: "es-MX"
      REGION: "es-MX"
      RAM_SIZE: "9G"
      CPU_CORES: "4"
      DISK_SIZE: "180G"
      DISK1_SIZE: "180G"
    devices:
      - /dev/kvm
      - /dev/nvme0n1p2:/disk1
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 80:80
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    mem_reservation: 11776m  # config max mem_reservation
    mem_limit: 11776m         # config max mem_limit
    cpus: 4 
    volumes:
      - /home/botom/Music/Win11_23H2_English_x64v2.iso:/custom.iso
      - /home/botom/Projects/Teravision/windows/install:/oem
    # volumes:
    #   - /run/media/botom/second/myvol:/storage

      
#  rtl8139